module.exports = (match) ->
  match '', 'home#index'
  match '', 'home#list_projects'
  match 'col/:collection', 'home#list_projects'
  match 'col/:collection/:filter', 'home#list_projects'
  match 'view/project/:id', 'home#get_project'
  match 'view/signup', 'home#signup'
  match 'view/projectLauncher', 'home#launch_project'
  match 'view/advanceSearch', 'home#advanceSearch'
  match 'view/userProfile', 'home#userProfile'
